version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    restart: always

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    restart: always
